#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgres_ready(){
python << END
import sys

import asyncpg
import asyncio
import os
async def connect_to_db():
  try:
    await asyncpg.connect(
      host=os.getenv('POSTGRES_HOST'),
      port=os.getenv('POSTGRES_PORT'),
      user=os.getenv('POSTGRES_USER'),
      password=os.getenv('POSTGRES_PASSWORD'),
      database=os.getenv('POSTGRES_DB'),
    )
  except asyncpg.exceptions.PostgresError:
    sys.exit(-1)
asyncio.run(connect_to_db())
sys.exit(0)

END
}
until postgres_ready; do
    >&2 echo 'Waiting for PostgreSQL to become available...'
    sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"